spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: mtrCdQIuhi9lx9cDpPsJ
            client-secret: aVoYtfjUi6
            redirect-uri: http://localhost:8080 #/auth/login
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - profile_image
        provider:
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response